### ISSUE TITLE
Catalog of my things - Kanban review

### ISSUE THREAD

**Issue by lu-jim** [lu-jim/catalog-of-my-things#34]
# Catalog of my things - Kanban review
[Link to the project](https://github.com/lu-jim/catalog-of-my-things) 
Number of people in the team: 3
- Team member # 1 - @mutinhiri 
- Team member # 2 - @sj1978 
- Team member # 3 - @lu-jim

**Comment by eri8-9** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

- Well done!

![Felix](https://media.giphy.com/media/hlQeY3PbhH3i/giphy.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
